# Generated by Django 5.0.6 on 2024-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_sharechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
